### PR TITLE
Readme: Russian Translation

### PR DESCRIPTION
**Pull request by zhadyrassyn**

### CODE REVIEW

**Comment by zhadyrassyn** [comment]
Hi. It is my first PR. Let me know if something is wrong.

**Comment by rjoydip** [comment]
Nice job :+1:

**Comment by zhadyrassyn** [comment]
@rjoydip Thank you so much. It means a lot for me!

**Comment by zhadyrassyn** [comment]
Just want to say thanks, guys! It is my first contribution ever and it got me started =)

**Pull request merged**
