### PR TITLE
Fix to tb -h problem at issue #46

### PR DESCRIPTION
**Pull request by SakhirAtwi**
Actually a fix was done before but issue is now  again occurring. Fixed the cli.js for that.

Screenshot is here,
screenshot_20180804_133420

### CODE REVIEW

**Comment by rjoydip** [comment]
duplicate https://github.com/klauscfhq/taskbook/pull/14/files

**Comment by SakhirAtwi** [comment]
Wait, what? Sorry I thought the the fix was applied and then got removed.. Now I notice that the earlier PR didn't merge in the first place.

**Comment by SakhirAtwi** [comment]
It's a pretty simple fix, I don't know why the owner won't merge it. As he didn't merge it 3 days back, the consequence was that another guy issued a new issue which i read and created the fix again. After all of that has happened, we are still on square one.

**Comment by klauscfhq** [comment]
Fixed on #14.
Thank you for taking the time to submit the pull request : )

**Pull request closed without merging**
